[package]
name = "nimino-chirps"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
alopex-chirps = { workspace = true }

[dev-dependencies]
rcgen = "0.12"
tempfile = "3"
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time"] }
